finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('investments/', views.list, name='list'),
    path('investments/<int:id>/', views.detail, name='detail'),
    path('investments/create/', views.InvestmentCreate.as_view(), name='create_investment'),
    path('investments/<int:pk>/update/', views.InvestmentUpdate.as_view(), name='update_investment'),
    path('investments/<int:pk>/delete/', views.InvestmentDelete.as_view(), name='delete_investment'),
    path('investments/<int:id>/add_prediction/', views.add_prediction, name='add_prediction'),
    path('remove_prediction/<int:prediction_id>/', views.remove_prediction, name='remove_prediction'),
    path('investments/<int:id>/assoc_source/<int:source_id>/', views.assoc_source, name='assoc_source'),
    path('investments/<int:id>/unassoc_source/<int:source_id>/', views.unassoc_source, name='unassoc_source'),
    path('sources/', views.SourceList.as_view(), name='list_source'),
    path('sources/create/', views.SourceCreate.as_view(), name='create_source'),
    path('sources/<int:pk>/update/', views.SourceUpdate.as_view(), name='update_source'),
    path('sources/<int:pk>/delete/', views.SourceDelete.as_view(), name='delete_source'),
    path('sources/<int:pk>/', views.SourceDetail.as_view(), name='source_detail'),
]

main_app/models.py
from django.db import models

from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

PAYMENTS = (
  ('CC', 'Credit Card'),
  ('CA', 'Cash'),
  ('WT', 'Wire Transfer'),
  ('CR', 'Cryptocurrency')
)

class Source(models.Model):
  name = models.CharField(max_length=100)
  amount = models.IntegerField()
  date = models.DateField('Bought on')
  payment_method = models.CharField(
    'Payment Method',
    max_length=2,
    choices=PAYMENTS,
    default=PAYMENTS[0][0]
  )

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('list_source')

  class Meta:
    ordering = ['-date']

class Investment(models.Model):
  name = models.CharField(max_length=100)
  amount = models.IntegerField()
  description = models.TextField(max_length=500)
  sources = models.ManyToManyField(Source)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('detail', kwargs={'id': self.id})

  def has_sources(self):
    return len(self.sources.all()) > 0 

class Prediction(models.Model):
  date = models.DateField('Predicted on')
  amount = models.IntegerField()
  investment = models.ForeignKey(Investment, on_delete=models.CASCADE)

  def __str__(self):
    return self.amount

  def get_absolute_url(self):
    return reverse('detail', kwargs={'id': self.id})

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Prediction

class PredictionForm(ModelForm):
  class Meta:
    model = Prediction
    fields = ['date', 'amount']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from .models import Investment, Source, Prediction

from .forms import PredictionForm

def home(request):
    return render(request, 'home.html')

def list(request):
  investments = Investment.objects.all()
  return render(request, 'investments/index.html', { 'investments': investments })

def detail(request, id):
  investment = Investment.objects.get(id=id)
  sources = Source.objects.exclude(id__in=investment.sources.all().values_list('id')).all()
  prediction_form = PredictionForm()
  return render(request, 'investments/detail.html', {
    'investment': investment,
    'prediction_form': prediction_form,
    'sources': sources
  })

class InvestmentCreate(CreateView):
  model = Investment
  fields = ['name', 'amount', 'description']

class InvestmentUpdate(UpdateView):
  model = Investment
  fields = ['amount', 'description']

class InvestmentDelete(DeleteView):
  model = Investment
  success_url = '/investments/'

def add_prediction(request, id):
  form = PredictionForm(request.POST)
  if form.is_valid():
    prediction = form.save(commit=False)
    prediction.investment_id = id
    prediction.save()
  return redirect('detail', id=id)

def remove_prediction(request, prediction_id):
  prediction = Prediction.objects.get(id=prediction_id)
  investment_id = prediction.investment.id
  prediction.delete()
  return redirect('detail', id=investment_id)

class SourceList(ListView):
  model = Source

class SourceDetail(DetailView):
  model = Source

class SourceCreate(CreateView):
  model = Source
  fields = '__all__'

class SourceUpdate(UpdateView):
  model = Source
  fields = ['name', 'amount', 'payment_method']

class SourceDelete(DeleteView):
  model = Source
  success_url = '/sources/'

def assoc_source(request, id, source_id):
  Investment.objects.get(id=id).sources.add(source_id)
  return redirect('detail', id=id)

def unassoc_source(request, id, source_id):
  Investment.objects.get(id=id).sources.remove(source_id)
  return redirect('detail', id=id)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Finch Collector</title>
</head>
<body>
    <nav>
        <h1><a href="{% url 'home' %}">Investis</a></h1>
        <ul>
            <li><a href="{% url 'create_source' %}">Add a Source</a></li>
            <li><a href="{% url 'list_source' %}">View All Sources</a></li>
            <li><a href="{% url 'create_investment' %}">Add an Investment</a></li>
            <li><a href="{% url 'list' %}">View All Investments</a></li>
        </ul>
    </nav>
    <main class="container">
    {% block content %}
    {% endblock %}
    </main>
    <footer>Investis ©</footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class='home-thumbnail'>
    <div>
        <p>Record all your investments</p>
        <a class='home-btn' href="{% url 'create_investment' %}">Get started</a>
    </div>
    <img id='home-img' src="{% static 'images/coin.jpeg' %}"/>
    <div class='overlay'></div>
</div>
<h2>Discover popular assets</h2>
<div class='home-assets'>
    <div>
        <img src={% static 'images/bitcoin2.jpeg' %} />
        <div class='overlay'></div>
    </div>
    <div>
        <img src={% static 'images/ethereum.jpeg' %} />
        <div class='overlay'></div>
    </div>
    <div>
        <img src={% static 'images/dogecoin.jpeg' %} />
        <div class='overlay'></div>
    </div>
</div>
{% endblock %}

main_app/templates/investments/detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class='investment-name'>{{ investment.name }}
</h1>
<div class='investment-detail'>
    <p>{{ investment.description }}</p>
    <p>Price: {{ investment.amount }}</p>
</div>

<div class='detail-links'>
    <a class='detail-link' href="{% url 'update_investment' investment.id %}">Edit</a>
    <a class='detail-link' href="{% url 'delete_investment' investment.id %}">Delete</a>
</div>

<form class="detail-form" action="{% url 'add_prediction' investment.id %}" method="POST">
    {% csrf_token %}
    {{ prediction_form.as_p }}
    <input type="submit" class="btn" value="Add Prediction">
</form>

<p class='detail-title'>Predictions</p>
{% if not prediction.count %}
    <p class='placeholder-text'>add a prediction...</p>
{% endif %}
{% for prediction in investment.prediction_set.all %}
    <div>
        <p>{{ prediction.amount }}</p>
        <a href={% url 'remove_prediction' prediction.id %}>Remove</a>
    </div>
{% endfor %}

<p class='detail-title'>Sources for this investment:</p>
{% if investment.has_sources %}
    <div class='card-container'>
        {% for source in investment.sources.all %}
        <div class='card'>
            <a href="{% url 'source_detail' source.id %}">{{source.name}}</a>
            <div class='card-action'>
                <a class='card-action-link' href="{% url 'unassoc_source' investment.id source.id %}">REMOVE</a>
            </div>
        </div>
        {% endfor %}‡
    </div>
    </hr>
{% else %}
    <p class='placeholder-text'>add a source...</p>
{% endif %}

<p class='detail-title'>Sources you can add:</p>
<div class='card-container'>
{% for source in sources %}
    <div class='card'>
        <a href="{% url 'source_detail' source.id %}">{{source.name}}</a>
        <div class='card-action'>
            <a class='card-action-link' href="{% url 'assoc_source' investment.id source.id %}">ADD</a>
        </div>
    </div>
{% endfor %}
{% if not sources.count %}
    <p class='placeholder-text'>all sources are added...</p>
{% endif %}
</div>
{% endblock %}

main_app/templates/investments/index.html
{% extends 'base.html' %}
{% block content %}

<div class='card-container'>
{% for investment in investments %}
    <div class='card'>
        <a href="{% url 'detail' investment.id%}">{{ investment.name }}</a>
        <div class='card-action'>
            <a class='card-action-link' href="{% url 'update_investment' investment.id %}">EDIT</a>
            <a class='card-action-link' href="{% url 'delete_investment' investment.id %}">DELETE</a>
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}

main_app/templates/main_app/investment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Investment</h1>

  <h4>Are you sure you want to delete <span>{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!">
    <a href="{% url 'detail' investment.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/investment_form.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="POST" autocomplete='off'>
  {% if object %}
    <a class='back' href="{% url 'detail' investment.id %}">back</a>
    <h2>Edit {{object.name}}</h2>
  {% else %}
    <h1>Add Investment</h1>
  {% endif %}
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="SUBMIT" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/source_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Source</h1>

  <h4>Are you sure you want to delete <span>{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'source_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/source_detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class='investment-name'>{{ source.name }}
</h1>
<div class='investment-detail'>
    <p>{{ source.amount }}</p>
    <p>Price: {{ source.payment_method }}</p>
</div>

<div class='detail-links'>
    <a class='detail-link' href="{% url 'update_source' source.id %}">Edit</a>
    <a class='detail-link' href="{% url 'delete_source' source.id %}">Delete</a>
</div>

{% endblock %}

main_app/templates/main_app/source_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <a class='back' href="{% url 'source_detail' source.id %}">back</a>
  <h1>Edit <span>{{object.name}}</span></h1>
{% else %}
  <h1>Add Source</h1>
{% endif %}

<form action="" method="POST" autocomplete='off'>
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/source_list.html
{% extends 'base.html' %}
{% block content %}

<div class='card-container'>
{% for source in source_list %}
    <div class='card'>
        <a href="{% url 'source_detail' source.id %}">{{source.name}}</a>
        <div class='card-action'>
            <a class='card-action-link' href="{% url 'update_source' source.id %}">EDIT</a>
            <a class='card-action-link' href="{% url 'delete_source' source.id %}">DELETE</a>
        </div>
    </div>
{% endfor %}
</div>

{% endblock %}